### ISSUE TITLE
Support for Nested YAML Front Matter Dicts

### ISSUE THREAD

**Issue by cloudrck** [eggcaker/jekyll-org#58]
Hello,

I'm working with a [Jekyll theme](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#headers) that allows header images and captions for each blog post. It works with the following YAML.

```yaml
header:
  image: /assets/images/unsplash-image-1.jpg
  caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
```

The variables are nested under the header dictionary. But as far as I can tell, jekyll-org does not support these types of variables. 

My question: How hard would this be to implement; or is this functionality supported and I'm just missing the correct org syntax?
